# TODO: needs to be updated for sj
# services:
#   ultraviolet:
#     image: diffusehyperion/ultraviolet
#     container_name: scramjet
#     restart: unless-stopped
#     ports:
#       - "4001:4001"

# networks:
#   default:
#     name: ultraviolet
